/**
 * Markdown Generator
 * Generates platform-aware Markdown representation of course/playlist/video data.
 */
const MarkdownGenerator = {
  formatSecondsToTimeStr(seconds) {
    if (isNaN(seconds) || seconds <= 0) return "00:00";
    const hrs = Math.floor(seconds / 3600);
    const mins = Math.floor((seconds % 3600) / 60);
    const secs = Math.floor(seconds % 60);
    if (hrs > 0) {
      return `${hrs}:${mins.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`;
    }
    return `${mins.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`;
  },

  generate(data) {
    if (!data) return "";
    
    const isYouTube = data.platform === "youtube";
    const isVideo = data.type === "video";
    
    // Standalone YouTube Video Layout
    if (isYouTube && isVideo) {
      const currentTimestamp = this.formatSecondsToTimeStr(data.progress?.currentTimeSeconds);
      const remainingTime = this.formatSecondsToTimeStr(data.progress?.remainingTimeSeconds);
      const videoId = data.url ? (typeof YouTubeExtractor !== "undefined" ? YouTubeExtractor.getVideoIdFromUrl(data.url) : "") : "";
      
      let md = `# Video Information\n\n`;
      md += `Title:\n${data.title}\n\n`;
      md += `Creator:\n${data.instructor}\n\n`;
      md += `Published:\n${data.publishDate || "Unknown"}\n\n`;
      md += `Video URL:\n${data.url || ""}\n\n`;
      md += `Duration:\n${data.duration}\n\n`;
      md += `Description:\n\n${data.description || ""}\n\n`;
      md += `---\n\n`;
      md += `# Learning Progress\n\n`;
      md += `Current Position:\n${currentTimestamp}\n\n`;
      md += `Progress:\n${data.progress?.percentComplete || 0}%\n\n`;
      md += `Remaining:\n${remainingTime}\n\n`;
      
      if (data.chapters && data.chapters.length > 0) {
        md += `---\n\n`;
        md += `# Chapters\n\n`;
        data.chapters.forEach((ch, index) => {
          md += `## Chapter ${index + 1}\n\n${ch.title}\n${ch.timeStr}\n\n`;
        });
      }
      
      md += `---\n\n`;
      md += `# Metadata\n\n`;
      md += `Platform:\nYouTube\n\n`;
      md += `Video ID:\n${videoId || ""}\n\n`;
      md += `Generated By:\nAI Ingest\n\n`;
      md += `Generated At:\n${new Date().toLocaleString()}\n`;
      
      return md.trim();
    }
    
    // YouTube Playlist Layout
    if (isYouTube && !isVideo) {
      let md = `# Playlist Information\n\n`;
      md += `Title:\n${data.title}\n\n`;
      md += `Creator:\n${data.instructor}\n\n`;
      md += `Playlist URL:\n${data.url || ""}\n\n`;
      md += `Duration:\n${data.duration}\n\n`;
      md += `Total Videos:\n${data.lecturesCount}\n\n`;
      md += `Description:\n\n${data.description || ""}\n\n`;
      md += `---\n\n`;
      md += `# Learning Progress\n\n`;
      md += `Completed Videos:\n${data.progress?.completedLecturesCount || 0}\n\n`;
      md += `Remaining Videos:\n${data.progress?.remainingLecturesCount || 0}\n\n`;
      md += `Progress:\n${data.progress?.percentComplete || 0}%\n\n`;
      md += `Current Video:\n${data.currentLecture?.title || "None"}\n\n`;
      md += `Current Position:\n${data.currentLecture ? `Video ${data.currentLecture.id} of ${data.lecturesCount}` : "None"}\n\n`;
      md += `---\n\n`;
      md += `# Current Video Description\n\n${data.currentLecture?.description || "No description available"}\n\n`;
      md += `---\n\n`;
      md += `# Playlist Structure\n\n`;
      
      const lectures = data.sections?.[0]?.lectures || [];
      lectures.forEach((lec, idx) => {
        const status = lec.isCurrent ? "Current" : (lec.completed ? "Completed" : "Incomplete");
        md += `## Video ${idx + 1}\n\n${lec.title}\n\n${lec.duration || "Unknown"}\n\n${status}\n\n`;
      });
      
      md += `---\n\n`;
      md += `# Metadata\n\n`;
      md += `Platform:\nYouTube Playlist\n\n`;
      md += `Generated By:\nAI Ingest\n\n`;
      md += `Generated At:\n${new Date().toLocaleString()}\n`;
      
      return md.trim();
    }
    
    // Standard Udemy Course Layout
    const instructorTerm = "Instructor";
    const lecturesTerm = "lectures";
    
    let md = `# ${data.title}\n\n`;
    if (data.instructor) md += `${instructorTerm}: ${data.instructor}\n`;
    if (data.duration) md += `Duration: ${data.duration}\n`;
    
    if (data.progress) {
      const p = data.progress;
      md += `Progress: ${p.percentComplete}% complete (${p.completedLecturesCount}/${p.totalLecturesCount} ${lecturesTerm}, ${p.completedSectionsCount}/${p.totalSectionsCount} sections completed)\n`;
    }
    
    if (data.currentLecture) {
      const cur = data.currentLecture;
      md += `Current Position: Section ${cur.sectionIndex + 1} - "${cur.sectionName}" > Lecture "${cur.title}"\n`;
    }
    md += `\n`;
    
    if (data.learningObjectives && data.learningObjectives.length > 0) {
      md += `## Learning Objectives\n`;
      data.learningObjectives.forEach(obj => {
        md += `* ${obj}\n`;
      });
      md += `\n`;
    }
    
    if (data.prerequisites && data.prerequisites.length > 0) {
      md += `## Prerequisites\n`;
      data.prerequisites.forEach(req => {
        md += `* ${req}\n`;
      });
      md += `\n`;
    }

    if (data.description) {
      md += `## Description\n${data.description}\n\n`;
    }
    
    md += `## Curriculum\n\n`;
    data.sections.forEach((sec, idx) => {
      const secStatus = sec.completed ? ' [COMPLETED]' : '';
      md += `### Section ${idx + 1} - ${sec.name}${secStatus}\n\n`;
      sec.lectures.forEach((lec) => {
        const durStr = lec.duration ? ` (${lec.duration})` : '';
        const check = lec.completed ? '[x]' : '[ ]';
        const currentMarker = lec.isCurrent ? ' <-- CURRENT POSITION' : '';
        md += `* ${check} ${lec.title}${durStr}${currentMarker}\n`;
      });
      md += `\n`;
    });
    
    return md.trim();
  }
};

if (typeof module !== "undefined" && module.exports) {
  module.exports = MarkdownGenerator;
}
